
[core]
R1 ansible_host=192.168.254.133 ansible_user=admin ansible_password=cisco

[core:vars]
nsible_connection=network_cli
ansible_network_os=ios
ansible_network_cli_ssh_type=paramiko
ansible_ssh_extra_args=-oKexAlgorithms=+diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no

