# Generated by Django 5.2.11 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMLSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('lab_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
